version: "3"

services:
  db:
    ##build: ./db   
    image: mysql
    # ports:
    #   - 3306:3306
    volumes:
      - ./db:/etc/mysql/conf.d
      - ./db/mysql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root 
      MYSQL_DATABASE: sample_db
      # MYSQL_USER: root 
      # MYSQL_PASSWORD: root 
      # MYSQL_MASTER: "true"

  api:
    build: .
    # links:
    #   - db
    # ports:
    #   - 9000
    # depends-on:
    #   - db

  proxy:
    build: ./proxy
    # links:
    #   - api:api
    ports:
      - 9000:80